from PyQt6 import QtWidgets, QtGui, QtCore
from jsonManager import JSONManager

class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(1400, 800)
        self.label = QtWidgets.QLabel(parent=Widget)
        self.label.setGeometry(QtCore.QRect(590, 20, 201, 20))
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(parent=Widget)
        self.tabWidget.setGeometry(QtCore.QRect(40, 80, 1301, 681))
        self.tabWidget.setObjectName("tabWidget")
        self.commandTab = QtWidgets.QWidget()
        self.commandTab.setObjectName("commandTab")
        self.exiftoolCommand = QtWidgets.QPlainTextEdit(parent=self.commandTab)
        self.exiftoolCommand.setGeometry(QtCore.QRect(30, 30, 1251, 371))
        self.exiftoolCommand.setObjectName("exiftoolCommand")
        self.loadFolder = QtWidgets.QPushButton(parent=self.commandTab)
        self.loadFolder.setGeometry(QtCore.QRect(520, 480, 100, 32))
        self.loadFolder.setObjectName("loadFolder")
        self.processJSON = QtWidgets.QPushButton(parent=self.commandTab)
        self.processJSON.setGeometry(QtCore.QRect(680, 480, 100, 32))
        self.processJSON.setObjectName("processJSON")
        self.processJSONProgress = QtWidgets.QProgressBar(parent=self.commandTab)
        self.processJSONProgress.setGeometry(QtCore.QRect(70, 530, 1211, 23))
        self.processJSONProgress.setProperty("value", 0)
        self.processJSONProgress.setObjectName("processJSONProgress")
        self.processJSONProgressLabel = QtWidgets.QLabel(parent=self.commandTab)
        self.processJSONProgressLabel.setGeometry(QtCore.QRect(57, 580, 1221, 41))
        self.processJSONProgressLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.processJSONProgressLabel.setObjectName("processJSONProgressLabel")
        self.tabWidget.addTab(self.commandTab, "commandTab")
        self.replaceMetadataTab = QtWidgets.QWidget()
        self.replaceMetadataTab.setObjectName("replaceMetadataTab")
        self.replaceTextLabel = QtWidgets.QLabel(parent=self.replaceMetadataTab)
        self.replaceTextLabel.setGeometry(QtCore.QRect(50, 80, 121, 16))
        self.replaceTextLabel.setObjectName("replaceTextLabel")
        self.notReplaceTextLabel = QtWidgets.QLabel(parent=self.replaceMetadataTab)
        self.notReplaceTextLabel.setGeometry(QtCore.QRect(30, 120, 141, 16))
        self.notReplaceTextLabel.setObjectName("notReplaceTextLabel")
        self.ReplaceText = QtWidgets.QPlainTextEdit(parent=self.replaceMetadataTab)
        self.ReplaceText.setGeometry(QtCore.QRect(180, 70, 231, 31))
        self.ReplaceText.setObjectName("ReplaceText")
        self.notReplace = QtWidgets.QPlainTextEdit(parent=self.replaceMetadataTab)
        self.notReplace.setGeometry(QtCore.QRect(180, 110, 231, 31))
        self.notReplace.setObjectName("notReplace")
        self.jsonFiles = QtWidgets.QPlainTextEdit(parent=self.replaceMetadataTab)
        self.jsonFiles.setGeometry(QtCore.QRect(630, 30, 621, 571))
        self.jsonFiles.setObjectName("jsonFiles")
        self.processJSONButton = QtWidgets.QPushButton(parent=self.replaceMetadataTab)
        self.processJSONButton.setGeometry(QtCore.QRect(230, 160, 100, 32))
        self.processJSONButton.setObjectName("processJSONButton")
        self.jsonProgress = QtWidgets.QProgressBar(parent=self.replaceMetadataTab)
        self.jsonProgress.setGeometry(QtCore.QRect(37, 490, 551, 23))
        self.jsonProgress.setProperty("value", 0)
        self.jsonProgress.setObjectName("jsonProgress")
        self.jsonProgressLabel = QtWidgets.QLabel(parent=self.replaceMetadataTab)
        self.jsonProgressLabel.setGeometry(QtCore.QRect(40, 530, 551, 16))
        self.jsonProgressLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.jsonProgressLabel.setObjectName("jsonProgressLabel")
        self.tabWidget.addTab(self.replaceMetadataTab, "replaceMetadataTab")
        self.writeMetadataTab = QtWidgets.QWidget()
        self.writeMetadataTab.setObjectName("writeMetadataTab")
        self.writeMetadataProgressLabel = QtWidgets.QLabel(parent=self.writeMetadataTab)
        self.writeMetadataProgressLabel.setGeometry(QtCore.QRect(60, 580, 1211, 20))
        self.writeMetadataProgressLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.writeMetadataProgressLabel.setObjectName("writeMetadataProgressLabel")
        self.writeMetadataProgress = QtWidgets.QProgressBar(parent=self.writeMetadataTab)
        self.writeMetadataProgress.setGeometry(QtCore.QRect(53, 540, 1221, 23))
        self.writeMetadataProgress.setProperty("value", 0)
        self.writeMetadataProgress.setObjectName("writeMetadataProgress")
        self.writeMetadataFolderList = QtWidgets.QPlainTextEdit(parent=self.writeMetadataTab)
        self.writeMetadataFolderList.setGeometry(QtCore.QRect(60, 50, 1201, 451))
        self.writeMetadataFolderList.setObjectName("writeMetadataFolderList")
        self.writeMetadataButton = QtWidgets.QPushButton(parent=self.writeMetadataTab)
        self.writeMetadataButton.setGeometry(QtCore.QRect(620, 610, 100, 32))
        self.writeMetadataButton.setObjectName("writeMetadataButton")
        self.tabWidget.addTab(self.writeMetadataTab, "writeMetadataTab")

        #Set Default State
        self.tabWidget.setCurrentIndex(0)
        self.replaceMetadataTab.setEnabled(True)
        self.writeMetadataTab.setEnabled(True)
        self.exiftoolCommand.setPlainText(
            "exiftool -r -progress -j --ext .txt --ext .csv --ext .db --ext .args --ext .json -exif:DateTimeOriginal -exif:ModifyDate -exif:Model -exif:CameraModelName -exif:ISO -exif:Notes -exif:ImageDescription -exif:UserComment -exif:GPSLongitude -exif:GPSLatitude -iptc:Sub-location -iptc:City -iptc:Province-State -iptc:Country-PrimaryLocationName -iptc:Category -iptc:Headline -iptc:Caption -iptc:Source -iptc:Caption-Abstract -iptc:Notes -iptc:FixtureIdentifier -iptc:Contact -iptc:Keywords -xmp:Event -xmp:Location -xmp:Sub-location -xmp:City -xmp:Province-State -xmp:Country-PrimaryLocationName -xmp:Description -xmp:UserComment -xmp:Keywords -xmp:People -xmp:PersonInImage -xmp:TagsList -xmp:CatalogSets -xmp:HierarchicalSubject -xmp:RegionAppliedToDimensions -xmp:RegionArea -xmp:RegionExtensions -xmp:RegionName -xmp:RegionPersonDisplayName -xmp:RegionRectangle -xmp:RegionType -xmp:RegionUnit")
        font = QtGui.QFont()
        font.setPointSize(24)
        self.exiftoolCommand.setFont(font)

        self.retranslateUi(Widget)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.label.setText(_translate("Widget", "Remove Metadata from Library"))
        self.loadFolder.setText(_translate("Widget", "Load Folder"))
        self.processJSON.setText(_translate("Widget", "Process JSON"))
        self.processJSONProgressLabel.setText(_translate("Widget", "Output"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.commandTab), _translate("Widget", "Command"))
        self.replaceTextLabel.setText(_translate("Widget", "Text to Replace"))
        self.notReplaceTextLabel.setText(_translate("Widget", "Text Not to Replace"))
        self.processJSONButton.setText(_translate("Widget", "Process JSON"))
        self.jsonProgressLabel.setText(_translate("Widget", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.replaceMetadataTab), _translate("Widget", "Replace Metadata"))
        self.writeMetadataProgressLabel.setText(_translate("Widget", "TextLabel"))
        self.writeMetadataButton.setText(_translate("Widget", "Write Metadata"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.writeMetadataTab), _translate("Widget", "Write Metadata"))
